# Generated by Django 5.2.6 on 2025-09-12 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_product_description_alter_product_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
    ]
